# -*- coding: utf-8 -*-
"""Cardiovascular Predictive Modeling

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pP1IXIRjIK86eoZ3g6qSMxOKDODmIBkH
"""

#Importing libraries needed for the project
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats

# Using pandas to load in SAS files
pd.set_option('display.float_format', lambda x: '%.6f' % x)
CHOL = pd.read_sas("C:\\Users\\deona\\Downloads\\Python FP\\TCHOL_L.xpt", format='xport')
DEMO = pd.read_sas("C:\\Users\\deona\\Downloads\\Python FP\\DEMO_L.xpt", format='xport')
DIET = pd.read_sas("C:\\Users\\deona\\Downloads\\Python FP\\DR1TOT_L.xpt", format='xport')
BP = pd.read_sas("C:\\Users\\deona\\Downloads\\Python FP\\BPXO_L.xpt", format='xport')

#Sorting data by SEQN(Participant ID)
DIET_sorted = DIET.sort_values(by="SEQN")
DEMO_sorted = DEMO.sort_values(by="SEQN")
CHOL_sorted = CHOL.sort_values(by="SEQN")
BP_sorted = BP.sort_values(by="SEQN")

#Merging SAS files on SEQN
Projectdf1 = (
    DEMO_sorted
    .merge(DIET_sorted, on="SEQN", how="inner")
    .merge(BP_sorted, on="SEQN", how="inner")
    .merge(CHOL_sorted, on="SEQN", how="inner")
)

#Converting merged file into a dataframe
df = pd.DataFrame(Projectdf1)

df

#Converting unmeasurable responses to NaN
df['LBXTC'] = df['LBXTC'].replace(['.'], np.nan)
df['BPXOSY1'] = df['BPXOSY1'].replace(['.'], np.nan)
df['BPXODI1'] = df['BPXODI1'].replace(['.'], np.nan)
df['DR1TPROT'] = df['DR1TPROT'].replace(['.'], np.nan)
df['DR1TSUGR'] = df['DR1TSUGR'].replace(['.'], np.nan)
df['DR1TFIBE'] = df['DR1TFIBE'].replace(['.'], np.nan)
df['DR1TTFAT'] = df['DR1TTFAT'].replace(['.'], np.nan)

#Handling missing values
df['LBXTC'] = df['LBXTC'].fillna(df['LBXTC'].mean())
df['BPXOSY1'] = df['BPXOSY1'].fillna(df['BPXOSY1'].mean())
df['BPXODI1'] = df['BPXODI1'].fillna(df['BPXODI1'].mean())
df['DR1TPROT'] = df['DR1TPROT'].fillna(df['DR1TPROT'].mean())
df['DR1TSUGR'] = df['DR1TSUGR'].fillna(df['DR1TSUGR'].mean())
df['DR1TFIBE'] = df['DR1TFIBE'].fillna(df['DR1TFIBE'].mean())
df['DR1TTFAT'] = df['DR1TTFAT'].fillna(df['DR1TTFAT'].mean())

#Selecting needed variables for research questions
df1 = df[['LBXTC', 'BPXOSY1','BPXODI1','DR1TPROT','DR1TSUGR','DR1TFIBE', 'DR1TTFAT']]

#Renaming variables for readibility
df1 = df1.rename(columns={'LBXTC': 'Cholesterol', 'BPXOSY1': 'Systolic','BPXODI1': 'Diastolic', 'DR1TPROT': 'Protein','DR1TSUGR': 'Sugar', 'DR1TFIBE': 'Fiber','DR1TTFAT': 'Fat' })

#Creating variable for blood pressure
df1["Total_BP"]= df1["Systolic"]/df1["Diastolic"]

df1.head(5)

#Selecting to use the first 200 participant since dataset is large
df2 = df1.head(200)

# Creating a plot to view the association between variables of interest
sns.regplot(x="Protein", y="Cholesterol", data=df2)
plt.tight_layout()
plt.show()
pearson_coef, p_value = stats.pearsonr(df2["Protein"], df2["Cholesterol"])
print("Pearson Correlation Coefficient:", pearson_coef)
print("P-value:", p_value)

# Creating a plot to view the association between variables of interest
sns.regplot(x="Sugar", y="Cholesterol", data=df2)
plt.tight_layout()
plt.show()
pearson_coef, p_value = stats.pearsonr(df2["Sugar"], df2["Cholesterol"])
print("Pearson Correlation Coefficient:", pearson_coef)
print("P-value:", p_value)

# Creating a plot to view the association between variables of interest
sns.regplot(x="Fiber", y="Cholesterol", data=df2)
plt.tight_layout()
plt.show()
pearson_coef, p_value = stats.pearsonr(df2["Fiber"], df2["Cholesterol"])
print("Pearson Correlation Coefficient:", pearson_coef)
print("P-value:", p_value)

# Creating a plot to view the association between variables of interest
sns.regplot(x="Fat", y="Cholesterol", data=df2)
plt.tight_layout()
plt.show()
pearson_coef, p_value = stats.pearsonr(df2["Fat"], df2["Cholesterol"])
print("Pearson Correlation Coefficient:", pearson_coef)
print("P-value:", p_value)

# Creating a plot to view the association between variables of interest
sns.regplot(x="Protein", y="Total_BP", data=df2)
plt.tight_layout()
plt.show()
pearson_coef, p_value = stats.pearsonr(df2["Protein"], df2["Total_BP"])
print("Pearson Correlation Coefficient:", pearson_coef)
print("P-value:", p_value)

# Creating a plot to view the association between variables of interest
sns.regplot(x="Sugar", y="Total_BP", data=df2)
plt.tight_layout()
plt.show()
pearson_coef, p_value = stats.pearsonr(df2["Sugar"], df2["Total_BP"])
print("Pearson Correlation Coefficient:", pearson_coef)
print("P-value:", p_value)

# Creating a plot to view the association between variables of interest
sns.regplot(x="Fiber", y="Total_BP", data=df2)
plt.tight_layout()
plt.show()
pearson_coef, p_value = stats.pearsonr(df2["Fiber"], df2["Total_BP"])
print("Pearson Correlation Coefficient:", pearson_coef)
print("P-value:", p_value)

# Creating a plot to view the association between variables of interest
sns.regplot(x="Fat", y="Total_BP", data=df2)
plt.tight_layout()
plt.show()
pearson_coef, p_value = stats.pearsonr(df2["Fat"], df2["Total_BP"])
print("Pearson Correlation Coefficient:", pearson_coef)
print("P-value:", p_value)

#Providing list to show variables that had the strongest relationship with outcome of interest
Colesterol
1.Sugar
Pearson Correlation Coefficient: -0.11732359229903346
P-value: 0.09802085794257709
2.Fiber
Pearson Correlation Coefficient: 0.11072230901036673
P-value: 0.11856196592298032
3.Fat
Pearson Correlation Coefficient: -0.027962891980154163
P-value: 0.6942802195356578
4.Protein
Pearson Correlation Coefficient: 0.004699370014165018
P-value: 0.9473436524725347

#Providing list to show variables that had the strongest relationship with outcome of interest
Total BP
1. Fiber
Pearson r = 0.0508
P-value = 0.4747
2. Protein
Pearson r = –0.0455
P-value = 0.5227
3. Sugar
Pearson r = 0.0420
P-value = 0.5549
4. Fat
Pearson r = –0.0011
P-value = 0.9872

# Fitting linear model with Sugar as the independent variable and cholesterol as the dependent variable
from sklearn.linear_model import LinearRegression

lm = LinearRegression()

x = df2[['Sugar']]
y = df2['Cholesterol']

lm.fit(x, y)

# Computing predicted y values
y_hat = lm.predict(x)

print("Predicted Price:", y_hat[0:5])
print("Actual Price:", y[0:5])

#Creating residuals plot to show difference between actual and predicted values
residuals = y - y_hat
sns.residplot(x=y_hat, y=residuals)
plt.show()

#Creating plot to show difference in distribution between actual and predicted values
sns.kdeplot(y, color='r', label="Actual Price")
sns.kdeplot(y_hat, color='b', label="Predicted Price")
plt.show()

# Getting metrics to test preformance of model
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

mse = mean_squared_error(y, y_hat)
out = r2_score(y, y_hat)

print('MSE:', mse)
print("R2 Score:", out)

# Fitting linear model with Fiber as the independent variable and cholesterol as the dependent variable
lm = LinearRegression()

x = df2[['Fiber']]
y = df2['Cholesterol']

lm.fit(x, y)

# Computing predicted y values
y_hat = lm.predict(x)

print("Predicted Price:", y_hat[0:5])
print("Actual Price:", y[0:5])

#Creating residuals plot to show difference between actual and predicted values
residuals = y - y_hat
sns.residplot(x=y_hat, y=residuals)
plt.show()

#Creating plot to show difference in distribution between actual and predicted values
sns.kdeplot(y, color='r', label="Actual Price")
sns.kdeplot(y_hat, color='b', label="Predicted Price")
plt.show()

# Getting metrics to test preformance of model
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

mse = mean_squared_error(y, y_hat)
out = r2_score(y, y_hat)

print('MSE:', mse)
print("R2 Score:", out)

# Fitting linear model with Fiber as the independent variable and blood pressure as the dependent variable
lm = LinearRegression()

x = df2[['Fiber']]
y = df2['Total_BP']

lm.fit(x, y)

# Computing predicted y values
y_hat = lm.predict(x)

print("Predicted Price:", y_hat[0:5])
print("Actual Price:", y[0:5])

#Creating residuals plot to show difference between actual and predicted values
residuals = y - y_hat
sns.residplot(x=y_hat, y=residuals)
plt.show()

#Creating plot to show difference in distribution between actual and predicted values
sns.kdeplot(y, color='r', label="Actual Price")
sns.kdeplot(y_hat, color='b', label="Predicted Price")
plt.show()

# Getting metrics to test preformance of model
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

mse = mean_squared_error(y, y_hat)
out = r2_score(y, y_hat)

print('MSE:', mse)
print("R2 Score:", out)

# Fitting linear model with Protien as the independent variable and blood pressure as the dependent variable
lm = LinearRegression()

x = df2[['Protein']]
y = df2['Total_BP']

lm.fit(x, y)

# Computing predicted y values
y_hat = lm.predict(x)

print("Predicted Price:", y_hat[0:5])
print("Actual Price:", y[0:5])

#Creating residuals plot to show difference between actual and predicted values
residuals = y - y_hat
sns.residplot(x=y_hat, y=residuals)
plt.show()

#Creating plot to show difference in distribution between actual and predicted values
sns.kdeplot(y, color='r', label="Actual Price")
sns.kdeplot(y_hat, color='b', label="Predicted Price")
plt.show()

# Getting metrics to test preformance of model
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

mse = mean_squared_error(y, y_hat)
out = r2_score(y, y_hat)

print('MSE:', mse)
print("R2 Score:", out)

#Creating function to remove outliers
def remove_outliers(df2, features):
  for feature in features:
    Q1 = df2[feature].quantile(0.25)
    Q3 = df2[feature].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    df2 = df2[(df2[feature] >= lower_bound) & (df2[feature] <= upper_bound)]

  return df2

df_cleaned = remove_outliers(df2, df2.loc[:, df2.columns != 'price'].columns)
df_cleaned = df_cleaned.reset_index(drop=True)
df_cleaned.head()

#Normalizing data in dataset to reduce biasness in models
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df_normalized = scaler.fit_transform(df_cleaned)
df_normalized = pd.DataFrame(df_normalized, columns=df_cleaned.columns)
df_normalized.head()

#Creating correlation matrix to view the variables with the strongest relationship with Cholesterol
corr_matrix = df_normalized.corr()
target_corr = corr_matrix['Cholesterol']
sorted_corr = target_corr.abs().sort_values(ascending=False)
sorted_corr

#Creating correlation matrix to view the variables with the strongest relationship with Cholesterol
corr_matrix = df_normalized.corr()
target_corr = corr_matrix['Total_BP']
sorted_corr = target_corr.abs().sort_values(ascending=False)
sorted_corr

#Fitting a multiple variable linear regression model
z = df_normalized[['Fiber','Protein','Sugar','Fat']]
y = df_normalized['Cholesterol']

mlr = LinearRegression()
mlr.fit(z, y)

# Getting metrics to test preformance of model
y_pred = mlr.predict(z)

mse = mean_squared_error(y, y_pred)
out = r2_score(y, y_pred)

print('MSE:', mse)
print('R2 Score:', out)

#Creating plot to show difference in distribution between actual and predicted values
sns.kdeplot(y, color='r', label="Actual Price")
sns.kdeplot(y_pred, color='b', label="Predicted Price")
plt.show()

#Fitting a multiple variable linear regression model
z = df_normalized[['Fiber','Protein','Sugar','Fat']]
y = df_normalized['Total_BP']

mlr = LinearRegression()
mlr.fit(z, y)

# Getting metrics to test preformance of model
y_pred = mlr.predict(z)

mse = mean_squared_error(y, y_pred)
out = r2_score(y, y_pred)

print('MSE:', mse)
print('R2 Score:', out)

#Creating plot to show difference in distribution between actual and predicted values
sns.kdeplot(y, color='r', label="Actual Price")
sns.kdeplot(y_pred, color='b', label="Predicted Price")
plt.show()

#Fitting polynomial model
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree=2)

x = df_normalized[['Fiber']]
y = df_normalized['Cholesterol']

x_transformed = poly.fit_transform(x)

x_poly_df = pd.DataFrame(x_transformed, columns=['Intercept', 'x', 'x^2'])

# Getting metrics to test preformance of model
plr = LinearRegression()
plr.fit(x_poly_df, y)

y_pred = plr.predict(x_poly_df)

mse = mean_squared_error(y, y_pred)
out = r2_score(y, y_pred)

print("MSE:", mse)
print("R2 Score", out)

#Creating plot to show difference in distribution between actual and predicted values
sns.kdeplot(y, color='r', label="Actual Price")
sns.kdeplot(y_pred, color='b', label="Predicted Price")
plt.show()

#Fitting polynomial model
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree=2)

x = df_normalized[['Protein']]
y = df_normalized['Total_BP']

x_transformed = poly.fit_transform(x)

x_poly_df = pd.DataFrame(x_transformed, columns=['Intercept', 'x', 'x^2'])

# Getting metrics to test preformance of model
plr = LinearRegression()
plr.fit(x_poly_df, y)

y_pred = plr.predict(x_poly_df)

mse = mean_squared_error(y, y_pred)
out = r2_score(y, y_pred)

print("MSE:", mse)
print("R2 Score", out)

#Creating plot to show difference in distribution between actual and predicted values
sns.kdeplot(y, color='r', label="Actual Price")
sns.kdeplot(y_pred, color='b', label="Predicted Price")
plt.show()

#Creating pipeline to fit used models while testing preformance
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split

x = df_normalized[['Fiber','Fat','Protein','Sugar']]
y = df_normalized['Cholesterol']

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size = 0.20, random_state=35
)

pipeline = Pipeline([
    ('poly', PolynomialFeatures(degree=2)),
    ('model', LinearRegression())
])

pipeline.fit(x_train, y_train)

y_pred = pipeline.predict(x_test)

mse = mean_squared_error(y_test, y_pred)
out = r2_score(y_test, y_pred)

print("MSE:", mse)
print("R2 Score:", out)

#Creating pipeline to fit Polynomial and Ridge models while testing preformance
from sklearn.linear_model import Ridge
pipeline = Pipeline([
    ('poly', PolynomialFeatures(degree=2)),
    ('model', Ridge(alpha=1.0))
])

pipeline.fit(x_train, y_train)

y_pred = pipeline.predict(x_test)

mse = mean_squared_error(y_test, y_pred)
out = r2_score(y_test, y_pred)

print("MSE:", mse)
print("R2 Score:", out)

#Creating plot to show difference in distribution between actual and predicted values
sns.kdeplot(y, color='r', label="Actual Cholesterol")
sns.kdeplot(y_pred, color='b', label="Predicted Cholesterol")
plt.show()

#Creating pipeline to fit Polynomial and Lasso models while testing preformance
from sklearn.linear_model import Lasso

pipeline = Pipeline([
    ('poly', PolynomialFeatures(degree=2)),
    ('model', Lasso(alpha=1.0))
])

pipeline.fit(x_train, y_train)

y_pred = pipeline.predict(x_test)

mse = mean_squared_error(y_test, y_pred)
out = r2_score(y_test, y_pred)

print("MSE:", mse)
print("R2 Score:", out)

#Creating plot to show difference in distribution between actual and predicted values
sns.kdeplot(y, color='r', label="Actual Cholesterol")
sns.kdeplot(y_pred, color='b', label="Predicted Cholesterol")
plt.show()

#Creating pipeline to fit Polynomial and Elastic Net models while testing preformance
from sklearn.linear_model import ElasticNet

pipeline = Pipeline([
    ('poly', PolynomialFeatures(degree=2)),
    ('model', ElasticNet(alpha=1.0, l1_ratio=0.2))
])

pipeline.fit(x_train, y_train)

y_pred = pipeline.predict(x_test)

mse = mean_squared_error(y_test, y_pred)
out = r2_score(y_test, y_pred)

print("MSE:", mse)
print("R2 Score:", out)

#Creating plot to show difference in distribution between actual and predicted values
sns.kdeplot(y, color='r', label="Actual Cholesterol")
sns.kdeplot(y_pred, color='b', label="Predicted Cholesterol")
plt.show()

#Creating pipeline to fit Polynomial and Linear Regression models while testing preformance
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split

x = df_normalized[['Fiber','Fat','Protein','Sugar']]
y = df_normalized['Total_BP']

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size = 0.20, random_state=35
)

pipeline = Pipeline([
    ('poly', PolynomialFeatures(degree=2)),
    ('model', LinearRegression())
])

pipeline.fit(x_train, y_train)

y_pred = pipeline.predict(x_test)

mse = mean_squared_error(y_test, y_pred)
out = r2_score(y_test, y_pred)

print("MSE:", mse)
print("R2 Score:", out)

#Creating pipeline to fit Polynomial and Ridge models while testing preformance
from sklearn.linear_model import Ridge
pipeline = Pipeline([
    ('poly', PolynomialFeatures(degree=2)),
    ('model', Ridge(alpha=1.0))
])

pipeline.fit(x_train, y_train)

y_pred = pipeline.predict(x_test)

mse = mean_squared_error(y_test, y_pred)
out = r2_score(y_test, y_pred)

print("MSE:", mse)
print("R2 Score:", out)

#Creating plot to show difference in distribution between actual and predicted values
sns.kdeplot(y, color='r', label="Actual Blood Pressure")
sns.kdeplot(y_pred, color='b', label="Predicted Blood Pressure")
plt.show()

#Creating pipeline to fit Polynomial and Lasso models while testing preformance
from sklearn.linear_model import Lasso

pipeline = Pipeline([
    ('poly', PolynomialFeatures(degree=2)),
    ('model', Lasso(alpha=1.0))
])

pipeline.fit(x_train, y_train)

y_pred = pipeline.predict(x_test)

mse = mean_squared_error(y_test, y_pred)
out = r2_score(y_test, y_pred)

print("MSE:", mse)
print("R2 Score:", out)

#Creating pipeline to fit Polynomial and Elastic Net models while testing preformance
from sklearn.linear_model import ElasticNet

pipeline = Pipeline([
    ('poly', PolynomialFeatures(degree=2)),
    ('model', ElasticNet(alpha=1.0, l1_ratio=0.2))
])

pipeline.fit(x_train, y_train)

y_pred = pipeline.predict(x_test)

mse = mean_squared_error(y_test, y_pred)
out = r2_score(y_test, y_pred)

print("MSE:", mse)
print("R2 Score:", out)

df1 = df[['LBXTC', 'BPXOSY1','BPXODI1','DR1TPROT','DR1TSUGR','DR1TFIBE', 'DR1TTFAT']]

df1["Cholesterol"].describe()

df1["Systolic"].describe()

df1["Diastolic"].describe()

df1["Protein"].describe()

df1["Sugar"].describe()

df1["Fiber"].describe()

df1["Fat"].describe()

