# -*- coding: utf-8 -*-
"""National Survey Data Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yn8Ejl6-VHe6YjM88HKBPxc1UswAqv_c
"""

# ============================================================
# NHANES DATA ANALYSIS PROJECT
# Python conversion of SAS program
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path


# ============================================================
# 1. SET DATA DIRECTORY
# SAS equivalent:
# libname NHANES '/home/u61677009/Data Analysis Project';
# ============================================================

DATA_DIR = Path("/home/u61677009/Data Analysis Project")


# ============================================================
# 2. IMPORT NHANES XPT FILES
# SAS equivalent:
# libname DPQ XPORT ".../DPQ_I.XPT";
# ============================================================

dpq = pd.read_sas(DATA_DIR / "DPQ_I.XPT", format="xport")
paq = pd.read_sas(DATA_DIR / "PAQ_I.XPT", format="xport")

# Your SAS filename contains a space before ".XPT".
# Change this filename if the actual file is named SMQ_I.XPT.
smq_file = DATA_DIR / "SMQ_I .XPT"

if not smq_file.exists():
    smq_file = DATA_DIR / "SMQ_I.XPT"

smq = pd.read_sas(smq_file, format="xport")
demo = pd.read_sas(DATA_DIR / "DEMO_I.XPT", format="xport")


# ============================================================
# 3. SORT DATASETS BY SEQN
# SAS equivalent:
# proc sort data=...;
# by SEQN;
# ============================================================

dpq = dpq.sort_values("SEQN")
paq = paq.sort_values("SEQN")
smq = smq.sort_values("SEQN")
demo = demo.sort_values("SEQN")


# ============================================================
# 4. MERGE ALL DATASETS
#
# SAS:
# merge dpq_i(in=a)
#       paq_i(in=b)
#       smq_i(in=c)
#       demo_i(in=d);
# by SEQN;
# if a and b and c and d;
#
# inner merge keeps participants present in all four datasets.
# ============================================================

projprac = (
    dpq
    .merge(paq, on="SEQN", how="inner")
    .merge(smq, on="SEQN", how="inner")
    .merge(demo, on="SEQN", how="inner")
)

print("\nMerged dataset dimensions:")
print(projprac.shape)

print("\nFirst five observations:")
print(projprac.head())


# ============================================================
# 5. FREQUENCY TABLE FOR DPQ020
# SAS equivalent:
# proc freq data=projprac;
# tables DPQ020;
# ============================================================

print("\nDPQ020 Frequency Table:")
print(
    projprac["DPQ020"]
    .value_counts(dropna=False)
    .sort_index()
)

print("\nMissing DPQ020 values:")
print(projprac["DPQ020"].isna().sum())


# ============================================================
# 6. CREATE PRAC1
# ============================================================

prac1 = projprac.copy()


# ------------------------------------------------------------
# Clean SMD650
#
# SAS:
# if smd650=. or smd650=999 or smd650=95
# then smd650=.;
# ------------------------------------------------------------

prac1["SMD650"] = prac1["SMD650"].replace(
    [999, 95],
    np.nan
)


# ------------------------------------------------------------
# Create SMOKE variable
#
# SAS:
# if SMQ040=. then SMQ040=.;
# else if SMQ040<=2 then SMOKE=1;
# else SMOKE=2;
#
# 1 = Smoke
# 2 = Don't Smoke
# ------------------------------------------------------------

prac1["SMOKE"] = np.select(
    [
        prac1["SMQ040"].isin([1, 2]),
        prac1["SMQ040"] > 2
    ],
    [
        1,
        2
    ],
    default=np.nan
)


# ------------------------------------------------------------
# Clean PAQ670 and create LPA
#
# SAS:
# if PAQ670=99 or PAQ670=. then PAQ670=.;
# else if PAQ670<3 then LPA=1;
# else LPA=2;
#
# 1 = Low
# 2 = Normal
# ------------------------------------------------------------

prac1["PAQ670"] = prac1["PAQ670"].replace(
    99,
    np.nan
)

prac1["LPA"] = np.select(
    [
        prac1["PAQ670"] < 3,
        prac1["PAQ670"] >= 3
    ],
    [
        1,
        2
    ],
    default=np.nan
)


# ============================================================
# 7. DESCRIPTIVE STATISTICS FOR AGE
# SAS equivalent:
# proc univariate data=prac1;
# var RIDAGEYR;
# ============================================================

print("\nRIDAGEYR Descriptive Statistics:")
print(prac1["RIDAGEYR"].describe())


# ============================================================
# 8. FREQUENCY TABLE FOR GENDER
# ============================================================

print("\nGender Frequency Table:")
print(
    prac1["RIAGENDR"]
    .value_counts(dropna=False)
    .sort_index()
)


# ============================================================
# 9. DEFINE SAS-LIKE FORMATS
# ============================================================

smq_labels = {
    1: "Every day",
    2: "Some days",
    3: "Not at all"
}

pa_labels = {
    1: "Low",
    2: "Normal"
}

smoke_labels = {
    1: "Smoke",
    2: "Don't Smoke"
}

depression_labels = {
    0: "Not at all",
    1: "Several Days",
    2: "More than half the days",
    3: "Nearly everyday",
    7: "Refused",
    8: "Don't know"
}

gender_labels = {
    1: "Male",
    2: "Female"
}


# ============================================================
# 10. CREATE PRAC2
#
# SAS:
# keep=RIDAGEYR SMD650 PAQ670 SMQ040
#      LPA SMOKE DPQ020 RIAGENDR
#
# if 18<=RIDAGEYR<=30 and RIAGENDR=1;
# if 1<=DPQ020<=3;
# ============================================================

prac2 = prac1[
    (prac1["RIDAGEYR"].between(18, 30)) &
    (prac1["RIAGENDR"] == 1) &
    (prac1["DPQ020"].between(1, 3))
].copy()

prac2 = prac2[
    [
        "RIDAGEYR",
        "SMD650",
        "PAQ670",
        "SMQ040",
        "LPA",
        "SMOKE",
        "DPQ020",
        "RIAGENDR"
    ]
]


# ============================================================
# 11. CREATE LABELED VARIABLES
#
# These are similar to SAS PROC FORMAT.
# Original numeric variables are preserved.
# ============================================================

prac2["Smoke_Frequency"] = prac2["SMQ040"].map(smq_labels)

prac2["Physical_Activity_Status"] = prac2["LPA"].map(pa_labels)

prac2["Smoke_Status"] = prac2["SMOKE"].map(smoke_labels)

prac2["Depression_Status"] = prac2["DPQ020"].map(
    depression_labels
)

prac2["Gender"] = prac2["RIAGENDR"].map(gender_labels)


# ============================================================
# 12. CHECK FINAL DATASET
# ============================================================

print("\nPRAC2 dimensions:")
print(prac2.shape)

print("\nPRAC2 first five observations:")
print(prac2.head())

print("\nPRAC2 column information:")
prac2.info()


# ============================================================
# 13. UNIVARIATE STATISTICS
# ============================================================

print("\nAge Statistics:")
print(prac2["RIDAGEYR"].describe())

print("\nPAQ670 Statistics:")
print(prac2["PAQ670"].describe())

print("\nSMD650 Statistics:")
print(prac2["SMD650"].describe())


# ============================================================
# 14. FREQUENCY TABLES
# ============================================================

print("\nGender Distribution:")
print(
    prac2["Gender"].value_counts(dropna=False)
)

print("\nSmoking Frequency:")
print(
    prac2["Smoke_Frequency"].value_counts(dropna=False)
)

print("\nDepression Status:")
print(
    prac2["Depression_Status"].value_counts(dropna=False)
)

print("\nSmoking Status:")
print(
    prac2["Smoke_Status"].value_counts(dropna=False)
)

print("\nPhysical Activity Status:")
print(
    prac2["Physical_Activity_Status"]
    .value_counts(dropna=False)
)


# Frequency tables from PRAC1

print("\nLPA Frequency - PRAC1:")
print(
    prac1["LPA"]
    .map(pa_labels)
    .value_counts(dropna=False)
)

print("\nSMOKE Frequency - PRAC1:")
print(
    prac1["SMOKE"]
    .map(smoke_labels)
    .value_counts(dropna=False)
)


# ============================================================
# GRAPHING FUNCTIONS
# ============================================================

def pie_chart(series, title):
    counts = series.dropna().value_counts()

    plt.figure(figsize=(7, 7))

    plt.pie(
        counts.values,
        labels=counts.index,
        autopct="%1.1f%%",
        startangle=90
    )

    plt.title(title)
    plt.tight_layout()
    plt.show()


def bar_chart(series, title, xlabel, ylabel):
    counts = series.dropna().value_counts()

    plt.figure(figsize=(8, 5))

    bars = plt.bar(
        counts.index.astype(str),
        counts.values
    )

    # SAS-like datalabel
    for bar in bars:
        height = bar.get_height()

        plt.text(
            bar.get_x() + bar.get_width() / 2,
            height,
            f"{int(height)}",
            ha="center",
            va="bottom"
        )

    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.title(title)
    plt.tight_layout()
    plt.show()


# ============================================================
# 15. PIE CHART — SMOKING STATUS
# ============================================================

pie_chart(
    prac2["Smoke_Status"],
    "Smoke Status Distribution"
)


# ============================================================
# 16. PIE CHART — GENDER
# ============================================================

pie_chart(
    prac2["Gender"],
    "Gender of Participant"
)


# ============================================================
# 17. PIE CHART — PHYSICAL ACTIVITY
# ============================================================

pie_chart(
    prac2["Physical_Activity_Status"],
    "Physical Activity Status Distribution Of Depressed Young Men"
)


# ============================================================
# 18. PIE CHART — DEPRESSION STATUS
# ============================================================

pie_chart(
    prac2["Depression_Status"],
    "Depression Status Distribution Of Depressed Young Men"
)


# ============================================================
# 19. BAR CHART — SMOKING FREQUENCY
# SAS:
# vbar SMQ040 / datalabel;
# ============================================================

bar_chart(
    prac2["Smoke_Frequency"],
    "Smoke Frequency/Distribution Of Depressed Young Men",
    "Smoke Frequency Status",
    "Total Number of Observations"
)


# ============================================================
# 20. HISTOGRAM — AGE
#
# SAS:
# histogram RIDAGEYR / scale=count;
# Xaxis values=(18 to 30 by 2);
# ============================================================

plt.figure(figsize=(8, 5))

plt.hist(
    prac2["RIDAGEYR"].dropna(),
    bins=np.arange(18, 32, 2),
    edgecolor="black"
)

plt.xticks(np.arange(18, 31, 2))

plt.xlabel("Age Range Of Participants")
plt.ylabel(
    "Number Of Observations That Fell In Particular Age Range"
)

plt.title(
    "Age Frequency/Distribution Of Depressed Young Men"
)

plt.tight_layout()
plt.show()


# ============================================================
# 21. HISTOGRAM — SMD650
# ============================================================

plt.figure(figsize=(8, 5))

plt.hist(
    prac2["SMD650"].dropna(),
    bins=np.arange(0, 22, 2),
    edgecolor="black"
)

plt.xticks(np.arange(0, 21, 2))

plt.xlabel("Smoking Frequency")
plt.ylabel(
    "Number Of Observations Who Had Similar Smoking Habits"
)

plt.title(
    "Smoking Frequency/Distribution Of Depressed Young Men"
)

plt.tight_layout()
plt.show()


# ============================================================
# 22. HISTOGRAM — PAQ670
# ============================================================

plt.figure(figsize=(8, 5))

plt.hist(
    prac2["PAQ670"].dropna(),
    bins=np.arange(-0.5, 8.5, 1),
    edgecolor="black"
)

plt.xticks(np.arange(0, 8, 1))

plt.xlabel("Moderate Exercise Frequency")
plt.ylabel(
    "Number Of Observations Who Had Similar Exercising Habits"
)

plt.title(
    "Moderate Exercise Frequency/Distribution Of Depressed Young Men"
)

plt.tight_layout()
plt.show()


# ============================================================
# 23. BAR CHART — PHYSICAL ACTIVITY STATUS
# ============================================================

bar_chart(
    prac2["Physical_Activity_Status"],
    "Physical Activity Status Distribution Of Depressed Young Men",
    "Physical Activity Status",
    "Total Number Of Observations"
)


# ============================================================
# 24. BAR CHART — SMOKING STATUS
# ============================================================

bar_chart(
    prac2["Smoke_Status"],
    "Smoking Status Distribution",
    "Smoking Status",
    "Total Number Of Observations"
)


# ============================================================
# 25. CREATE PRAC4 — SMOKERS ONLY
#
# SAS:
# data prac4;
# set prac1;
# if smoke=1;
# ============================================================

prac4 = prac1[
    prac1["SMOKE"] == 1
].copy()

print("\nNumber of smokers in PRAC4:")
print(len(prac4))


# ============================================================
# 26. AGE DISTRIBUTION OF SMOKERS
# ============================================================

plt.figure(figsize=(9, 5))

plt.hist(
    prac4["RIDAGEYR"].dropna(),
    bins=np.arange(20, 85, 5),
    edgecolor="black"
)

plt.xticks(np.arange(20, 81, 5))

plt.xlabel("Age Range Of Participants")
plt.ylabel(
    "Number Of Observations That Fell In Particular Age Range"
)

plt.title(
    "Age Frequency/Distribution Of Smokers"
)

plt.tight_layout()
plt.show()