# -*- coding: utf-8 -*-
"""credibility.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BIK-8p9Y9apsZkzWCbn7g7VWRPd7xbaw
"""

"""
credibility.py — THIS IS THE FILE YOU IMPROVE.
===============================================================================

Everything else in this project is scaffolding. The chatbot works, the UI works,
the tracing works. What does NOT work well is the function below: `score_url()`.

Your job for Project 1 is to make it better. Read the KNOWN WEAKNESSES section
at the bottom of this file — every item on that list is a bug you are invited to
fix, and every one of them is worth points.

-------------------------------------------------------------------------------
THE CONTRACT (do not change this)
-------------------------------------------------------------------------------
    score_url("https://arxiv.org/abs/1706.03762")

    -> {"score": 0.9, "explanation": "arxiv.org is a recognized preprint ..."}

    score:       float in [0.0, 1.0].  0 = not credible, 1 = highly credible.
    explanation: str. A human-readable reason for the score.

Your grader, the evaluation harness (`evaluate.py`), the test suite
(`test_credibility.py`), and the Streamlit app all depend on this exact shape.
If you change the keys or the types, everything downstream breaks.

-------------------------------------------------------------------------------
HOW THE BASELINE WORKS
-------------------------------------------------------------------------------
Two layers, combined at the end:

    Layer 1 (rules)  Pure string inspection of the URL. No network, no API key.
                     Always runs. This is why the app works before you have
                     configured anything.

    Layer 2 (LLM)    One Claude call that judges the URL. Only runs when
                     ANTHROPIC_API_KEY is set and `use_llm` is not False.
                     Skipped silently otherwise.

The final score is a weighted blend of the two. See `score_url()`.
"""

from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Tuple
from urllib.parse import urlparse
import math
import requests
from bs4 import BeautifulSoup
from dotenv import load_dotenv
load_dotenv(override=True)
# The model used for the Layer 2 judgment. Claude Opus 5 is the most capable
# model; switch to "claude-haiku-4-5" if you are scoring many URLs and want to
# cut cost, or "claude-sonnet-5" for a middle option. Scoring quality will move
# with this choice, so note in your report which model your numbers came from.
JUDGE_MODEL = "claude-opus-5"

# How much each layer contributes to the final score. These two must sum to 1.0.
# Tuning this split is one of the easiest wins available to you.
RULE_WEIGHT = 0.6
LLM_WEIGHT = 0.4

# =============================================================================
# LAYER 1 — RULE-BASED SIGNALS
# =============================================================================
# Each table below is a hand-written guess about what makes a source credible.
# They are deliberately short and deliberately naive. Extending them is the
# fastest way to improve your score on the evaluation set, but note that a
# longer lookup table is not the same thing as a better *algorithm* — the
# report asks you to justify your approach, not just your word list.

# Exact-domain judgments. Highest-confidence signal we have.
DOMAIN_SCORES: Dict[str, float] = {
    # Peer-reviewed / archival
    "nature.com": 0.95,
    "science.org": 0.95,
    "nejm.org": 0.95,
    "thelancet.com": 0.95,
    "pubmed.ncbi.nlm.nih.gov": 0.92,
    "arxiv.org": 0.75,          # preprint: NOT peer reviewed
    "biorxiv.org": 0.70,        # preprint: NOT peer reviewed
    # Reference
    "wikipedia.org": 0.65,
    "britannica.com": 0.80,
    # Mainstream press
    "reuters.com": 0.85,
    "apnews.com": 0.85,
    "bbc.com": 0.82,
    "nytimes.com": 0.80,
    "wsj.com": 0.80,
    # User-generated / self-published
    "medium.com": 0.35,
    "substack.com": 0.35,
    "blogspot.com": 0.25,
    "wordpress.com": 0.25,
    "reddit.com": 0.25,
    "quora.com": 0.20,
    "x.com": 0.15,
    "twitter.com": 0.15,
    # Satire — factually false by design, which the LLM layer often misses
    "theonion.com": 0.05,
    "clickhole.com": 0.05,
    "babylonbee.com": 0.05,
}

# Fallback when the exact domain is unknown. Coarse and easy to fool.
TLD_SCORES: Dict[str, float] = {
    ".gov": 0.88,
    ".edu": 0.70,
    ".mil": 0.85,
    ".org": 0.60,
    ".com": 0.50,
    ".net": 0.48,
    ".io": 0.45,
    ".biz": 0.30,
    ".info": 0.30,
    ".xyz": 0.25,
}

# Substrings in the URL path that hint at self-published or low-edit content.
PATH_PENALTIES: Dict[str, float] = {
    "/blog/": -0.10,
    "/opinion/": -0.08,
    "/sponsored/": -0.20,
    "/press-release/": -0.15,
    "/advertorial/": -0.25,
    "/forum/": -0.12,
    "/comments/": -0.12,
}

# Neutral starting point for a URL we know nothing about.
NEUTRAL_SCORE = 0.5

@dataclass
class Signal:
    """One piece of evidence that moved the score, kept so we can explain it."""

    name: str      # short machine-readable label, e.g. "known_domain"
    value: float   # the score or delta this signal contributed
    reason: str    # human-readable sentence for the explanation field


def _normalize_domain(url: str) -> str:
    """
    Pull a bare lowercase domain out of a URL.

    Strips the scheme, any userinfo, the port, and a leading "www.". Returns an
    empty string when the URL has no host at all, which the caller treats as a
    malformed input.
    """
    host = (urlparse(url).netloc or "").lower()
    host = host.split("@")[-1]      # drop user:pass@
    host = host.split(":")[0]       # drop :port
    if host.startswith("www."):
        host = host[4:]
    return host


def _match_known_domain(domain: str) -> Optional[Tuple[str, float]]:
    """
    Look the domain up in DOMAIN_SCORES, allowing subdomains to match.

    "en.wikipedia.org" matches the "wikipedia.org" entry, and "arxiv.org"
    matches itself. We check the exact domain first so a more specific entry
    always wins over a more general one.
    """
    if domain in DOMAIN_SCORES:
        return domain, DOMAIN_SCORES[domain]
    for known, score in DOMAIN_SCORES.items():
        if domain.endswith("." + known):
            return known, score
    return None


def rule_based_signals(url: str) -> List[Signal]:
    """
    Inspect the URL string and return every signal that fired.
    """
    signals: List[Signal] = []
    parsed = urlparse(url)
    domain = _normalize_domain(url)

    # Signal 1: exact or suffix match against our hand-written domain table.
    match = _match_known_domain(domain)

    if match:
        known, score = match
        signals.append(
            Signal(
                "known_domain",
                score,
                f"'{known}' is a domain we recognize"
            )
        )
    else:
        # Signal 2: fall back to the top-level domain.
        for tld, score in TLD_SCORES.items():
            if domain.endswith(tld):
                signals.append(
                    Signal(
                        "tld",
                        score,
                        f"'{tld}' domains score {score:.2f} by default"
                    )
                )
                break
        else:
            signals.append(
                Signal(
                    "unknown",
                    NEUTRAL_SCORE,
                    "unrecognized domain and TLD"
                )
            )

    # Signal 3: HTTPS.
    if parsed.scheme == "https":
        signals.append(
            Signal("https", 0.02, "served over HTTPS")
        )
    elif parsed.scheme == "http":
        signals.append(
            Signal("no_https", -0.05, "served over plain HTTP")
        )

    # Signal 4: path keywords.
    path = (parsed.path or "").lower()

    for fragment, delta in PATH_PENALTIES.items():
        if fragment in path:
            signals.append(
                Signal(
                    "path",
                    delta,
                    f"URL path contains '{fragment}'"
                )
            )

    # Signal 5: DOI.
    if re.search(r"/10\.\d{4,9}/", path):
        signals.append(
            Signal(
                "doi",
                0.10,
                "URL contains a DOI, suggesting a registered publication"
            )
        )

    return signals

def page_based_signals(url: str) -> List[Signal]:
    """
    Fetch the page and inspect credibility-related metadata.

    Looks for:
      - identifiable author
      - publication date
      - references/citations
      - corrections/retraction information
      - peer-review indicators
      - personal-page indicators on .edu sites

    Network or parsing failures return an empty list so that the
    original URL-based scorer can still operate.
    """
    signals: List[Signal] = []

    try:
        headers = {
            "User-Agent": (
                "Mozilla/5.0 (compatible; CredibilityScorer/1.0)"
            )
        }

        response = requests.get(
            url,
            headers=headers,
            timeout=5,
            allow_redirects=True,
        )

        response.raise_for_status()

        # Do not try to parse PDFs, images, downloads, etc. as HTML.
        content_type = response.headers.get("Content-Type", "").lower()

        if "html" not in content_type:
            return signals

        soup = BeautifulSoup(response.text, "html.parser")
        text = soup.get_text(" ", strip=True).lower()

    except (requests.RequestException, ValueError):
        return signals

    return signals

def page_based_signals(url: str) -> List[Signal]:
    """
    Fetch the page and inspect credibility-related metadata.
    """
    signals: List[Signal] = []

    try:
        headers = {
            "User-Agent": (
                "Mozilla/5.0 (compatible; CredibilityScorer/1.0)"
            )
        }

        response = requests.get(
            url,
            headers=headers,
            timeout=5,
            allow_redirects=True,
        )

        response.raise_for_status()

        # Do not try to parse PDFs, images, downloads, etc. as HTML.
        content_type = response.headers.get("Content-Type", "").lower()
        if "html" not in content_type:
            return signals

        soup = BeautifulSoup(response.text, "html.parser")
        text = soup.get_text(" ", strip=True).lower()

        # -------------------------------------------------------------
        # Signal 1: identifiable author
        # -------------------------------------------------------------
        author = (
            soup.find(
                "meta",
                attrs={"name": re.compile("^author$", re.I)}
            )
            or soup.find(
                "meta",
                attrs={"property": re.compile(r"article:author", re.I)}
            )
        )

        if author and author.get("content", "").strip():
            signals.append(
                Signal(
                    "page_author",
                    0.04,
                    "the page identifies an author",
                )
            )

        # -------------------------------------------------------------
        # Signal 2: publication date
        # -------------------------------------------------------------
        date_meta = (
            soup.find(
                "meta",
                attrs={
                    "property": re.compile(
                        r"article:(published_time|modified_time)",
                        re.I,
                    )
                },
            )
            or soup.find(
                "meta",
                attrs={
                    "name": re.compile(
                        r"(date|publication_date|publish-date|pubdate)",
                        re.I,
                    )
                },
            )
        )

        if date_meta and date_meta.get("content", "").strip():
            signals.append(
                Signal(
                    "publication_date",
                    0.03,
                    "the page provides publication-date metadata",
                )
            )

        # -------------------------------------------------------------
        # Signal 3: references / bibliography
        # -------------------------------------------------------------
        reference_terms = (
            "references",
            "bibliography",
            "works cited",
        )

        if any(term in text for term in reference_terms):
            signals.append(
                Signal(
                    "references",
                    0.06,
                    "the page appears to provide references or a bibliography",
                )
            )

        # -------------------------------------------------------------
        # Signal 4: corrections policy / correction information
        # -------------------------------------------------------------
        correction_terms = (
            "corrections policy",
            "correction policy",
            "submit a correction",
            "report an error",
        )

        if any(term in text for term in correction_terms):
            signals.append(
                Signal(
                    "corrections",
                    0.04,
                    "the page provides evidence of a corrections process",
                )
            )

        # -------------------------------------------------------------
        # Signal 5: retraction warning
        # -------------------------------------------------------------
        retraction_terms = (
            "this article has been retracted",
            "retraction notice",
            "retracted article",
            "this paper has been retracted",
        )

        if any(term in text for term in retraction_terms):
            signals.append(
                Signal(
                    "retraction",
                    -0.35,
                    "the page contains language indicating a retraction",
                )
            )

        # -------------------------------------------------------------
        # Signal 6: peer-review indicators
        # -------------------------------------------------------------
        peer_review_terms = (
            "peer reviewed",
            "peer-reviewed",
            "accepted manuscript",
            "received:",
            "accepted:",
        )

        if any(term in text for term in peer_review_terms):
            signals.append(
                Signal(
                    "peer_review",
                    0.08,
                    "the page contains indicators associated with peer review",
                )
            )

        # -------------------------------------------------------------
        # Signal 7: possible personal .edu page
        # -------------------------------------------------------------
        domain = _normalize_domain(url)
        path = urlparse(url).path.lower()

        if domain.endswith(".edu"):
            personal_patterns = (
                "/~",
                "/users/",
                "/people/",
                "/students/",
                "/student/",
                "/personal/",
                "/homepage/",
            )

            if any(pattern in path for pattern in personal_patterns):
                signals.append(
                    Signal(
                        "personal_edu",
                        -0.20,
                        "the URL appears to be a personal or student page "
                        "hosted on an educational domain",
                    )
                )

    except requests.RequestException:
        # Network problems must not break score_url().
        return signals

    except Exception:
        # Unexpected parsing problems also degrade gracefully.
        return signals

    return signals

_JUDGE_SYSTEM = """You assess the credibility of web sources for a research assistant.

Given a URL, judge how much a careful reader should trust content published there.
Consider: the publisher's editorial standards and reputation, whether the content is
peer reviewed, whether it is self-published, and whether the outlet is satirical.

Score 0.0 (not credible at all) to 1.0 (highly credible). Be skeptical of
self-published platforms and satire. Judge the SOURCE, not the topic. If you do not
recognize the domain, say so and score near 0.5 rather than guessing confidently."""

# Constraining the response to this schema means we never have to parse prose or
# repair malformed JSON — the API guarantees the shape.
_JUDGE_SCHEMA: Dict[str, Any] = {
    "type": "object",
    "properties": {
        "score": {"type": "number", "description": "Credibility from 0.0 to 1.0"},
        "reason": {"type": "string", "description": "One sentence justifying the score"},
    },
    "required": ["score", "reason"],
    "additionalProperties": False,
}

# =============================================================================
# ⚠️  NEEDS YOUR OWN API KEY — AND SHIPPED UNVERIFIED
# =============================================================================
# REQUIRES A KEY. This function is the only part of credibility.py that calls
# Anthropic. Without ANTHROPIC_API_KEY set it returns None and the scorer falls
# back to rules only — no error, just a weaker score. Get a key at
# https://console.anthropic.com/ and put it in `.env` (copy `.env.example`).
# The key is yours and the calls are billed to you, which is exactly why the
# rules layer, the tests, and evaluate.py were all built to run without one.
#
# VERIFIED LIVE. This path has been run against the real API: the
# `output_config` structured-output call returns a valid score and reason, and
# the blend measurably helps. On the 24-URL evaluation set, turning this layer
# on moves MAE from 0.142 to 0.086 and band accuracy from 66.7% to 83.3%.
#
# Where it helps most is the held-out domains the rule table has never seen —
# a JAMA article scores 0.52 on rules alone and 0.70 with this layer, because
# the model knows what JAMA is and the lookup table does not.
# =============================================================================


def llm_opinion(url: str) -> Optional[Signal]:
    """
    Ask Claude to judge the URL. Returns None whenever the call cannot be made.

    Returning None rather than raising is deliberate: a missing API key, a
    network blip, or a safety refusal should degrade the score to rules-only
    instead of taking down the whole app. Effort is set to "low" because this
    is a small judgment and we may be scoring several URLs per question.
    """
    if not os.getenv("ANTHROPIC_API_KEY"):
        print("DEBUG: ANTHROPIC_API_KEY was not found.")
        return None
    else:
        print("DEBUG: ANTHROPIC_API_KEY was found.")

    try:
        import anthropic

        client = anthropic.Anthropic()

        response = client.messages.create(
            model=JUDGE_MODEL,
            max_tokens=1024,
            system=_JUDGE_SYSTEM,
            messages=[
                {
                    "role": "user",
                    "content": f"Rate the credibility of this source: {url}",
                }
            ],
            output_config={
                "effort": "low",
                "format": {
                    "type": "json_schema",
                    "schema": _JUDGE_SCHEMA,
                },
            },
        )

        # Claude can decline a request; content is empty or partial when it does.
        if response.stop_reason == "refusal":
            return None

        text = next(
            (b.text for b in response.content if b.type == "text"),
            "",
        )

        data = json.loads(text)

        score = max(
            0.0,
            min(1.0, float(data["score"])),
        )

        return Signal(
            "llm",
            score,
            str(data["reason"]),
        )

    except Exception as e:
        print(f"Anthropic API error: {e}")
        return None

def _build_explanation(
    signals: List[Signal],
    final_score: float,
    llm: Optional[Signal] = None,
) -> str:
    """
    Explain why the evidence matters instead of simply listing
    which rules fired.
    """

    strengths: List[str] = []
    cautions: List[str] = []

    for signal in signals:

        if signal.name == "known_domain":
            strengths.append(
                "this publisher is recognized by the credibility system")

        elif signal.name == "https":
            strengths.append(
                "this connection uses HTTPS, although HTTPS alone does not establish true accuracy")

        elif signal.name == "doi":
            strengths.append(
                "this URL contains a DOI associated with the registered academic material")

        elif signal.name == "page_author":
            strengths.append(
                "this page identifies an author, improving accountability")

        elif signal.name == "publication_date":
            strengths.append(
                "publication-date information is available, making the source easier to place in context")

        elif signal.name == "references":
            strengths.append(
                "there are references or a bibliography present, allowing viewers to investigate supporting evidence")

        elif signal.name == "corrections":
            strengths.append(
                "a corrections process appears to be accessible , which supports transparency")

        elif signal.name == "peer_review":
            strengths.append(
                "this page contains indicators correlated with peer review")

        elif signal.name == "preprint":
            cautions.append(
                "this work is hosted on a preprint server and therefore should not automatically be treated as peer reviewed")

        elif signal.name == "personal_edu":
            cautions.append(
                "this page appears to be personal or student-hosted; the .edu address alone does not make its claims authoritative"
            )

        elif signal.name == "retraction":
            cautions.append(
                "this page contains a possible retraction warning, which substantially reduces confidence in the work")

        elif signal.name == "path":
            cautions.append(
                "this URL suggests opinion, sponsored, or otherwise less independently reviewed content")

        elif signal.name == "no_https":
            cautions.append(
                "this site is served over plain HTTP rather than HTTPS")

        elif signal.name == "unknown":
            cautions.append(
                "this publisher is not recognized, so reputation cannot be established from the domain alone")

    sentences: List[str] = []

    if strengths:
        sentences.append(
            "Positive indicators include " + "; ".join(strengths) + "."
        )

    if cautions:
        sentences.append(
            "Important cautions include " + "; ".join(cautions) + "."
        )

    if final_score >= 0.70:
        sentences.append(
            "The available collected evidence provides relatively strong "
            "support for this source, although the claims should still be tested."
        )

    elif final_score >= 0.40:
        sentences.append(
            "The evidence is mixed, so readers should verify important "
            "claims with additional sources."
        )

    else:
        sentences.append(
            "The available collected evidence provides limited support "
            "for relying on this source without independent verification."
        )

    if llm is not None:
        sentences.append(
            f"The model assessment additionally noted: {llm.reason}"
        )

    return " ".join(sentences)

# =============================================================================
# THE FUNCTION YOU ARE GRADED ON
# =============================================================================

# Scoring the same URL repeatedly in one session is common (a chat may cite the
# same paper on every turn), so results are memoized for the process lifetime.
_CACHE: Dict[Tuple[str, Optional[bool]], Dict[str, Any]] = {}


def score_url(url: str, use_llm: Optional[bool] = None) -> Dict[str, Any]:
    """
    Score the credibility of a source URL.

    :param url:     The URL to evaluate.
    :param use_llm: True forces the Claude judgment, False forces rules-only,
                    None (default) uses the LLM when an API key is available.
    :return:        {"score": float in [0,1], "explanation": str}
    """
    cache_key = (url, use_llm)

    if cache_key in _CACHE:
        return dict(_CACHE[cache_key])

    # Guard clause: anything that is not a usable http(s) URL scores 0.0 with an
    # explanation rather than raising, so one bad link cannot break a whole page.
    if not isinstance(url, str) or not url.strip():
        return {
            "score": 0.0,
            "explanation": "No URL was provided.",
        }

    parsed = urlparse(url.strip())

    if parsed.scheme not in ("http", "https") or not _normalize_domain(url):
        return {
            "score": 0.0,
            "explanation": f"'{url}' is not a valid http(s) URL.",
        }

    # Layer 1 always runs.
    signals = rule_based_signals(url)
    signals.extend(scholarly_status_signals(url))
    signals.extend(page_based_signals(url))
    rule_score = _combine_signals(signals)

    # Layer 2 runs only when it can. Blend if we got an opinion,
    # otherwise the rule score stands on its own.
    llm = llm_opinion(url) if use_llm is not False else None

    if llm is not None:
        final = RULE_WEIGHT * rule_score + LLM_WEIGHT * llm.value
    else:
        final = rule_score

    final = round(max(0.0, min(1.0, final)), 2)

    explanation = _build_explanation(
        signals,
        final,
        llm,
    )

    result = {
        "score": final,
        "explanation": explanation,
    }

    _CACHE[cache_key] = dict(result)

    return result

def score_band(score: float) -> Tuple[str, str]:
    """
    Map a score onto a display band. Used by the app to colour the source chips.

    :return: (label, streamlit_colour) — e.g. ("HIGH", "green")
    """
    if score >= 0.70:
        return "HIGH", "green"
    if score >= 0.40:
        return "MEDIUM", "orange"
    return "LOW", "red"

import numpy as np
import matplotlib.pyplot as plt

# Expected credibility scores from LABELLED_URLS
expected_scores = [
    0.93, 0.88, 0.65, 0.50, 0.05, 0.35,
    0.60, 0.10, 0.92, 0.85, 0.45, 0.85,
    0.05, 0.90, 0.15, 0.25, 0.95, 0.95,
    0.85, 0.75, 0.85, 0.90, 0.20, 0.05
]

# Predicted credibility scores from my evaluation output
predicted_scores = [
    0.70, 0.69, 0.81, 0.66, 0.20, 0.49,
    0.72, 0.21, 0.81, 0.74, 0.55, 0.75,
    0.14, 0.98, 0.20, 0.30, 0.99, 0.99,
    0.89, 0.79, 0.88, 0.93, 0.21, 0.05
]


def plot_calibration(expected_scores, predicted_scores):
    """
    Plot average expected credibility against average predicted
    credibility within score bins.
    """

    # Convert lists to NumPy arrays
    expected = np.asarray(expected_scores, dtype=float)
    predicted = np.asarray(predicted_scores, dtype=float)

    # Create five score bins:
    # 0.0-0.2, 0.2-0.4, 0.4-0.6, 0.6-0.8, 0.8-1.0
    bins = np.linspace(0.0, 1.0, 6)

    mean_predicted = []
    mean_expected = []

    # Calculate the average predicted and expected
    # score within each bin
    for lower, upper in zip(bins[:-1], bins[1:]):

        if upper == 1.0:
            mask = (predicted >= lower) & (predicted <= upper)
        else:
            mask = (predicted >= lower) & (predicted < upper)

        if np.any(mask):
            mean_predicted.append(predicted[mask].mean())
            mean_expected.append(expected[mask].mean())

    # Create the figure
    plt.figure(figsize=(7, 6))

    # Perfect calibration reference line
    plt.plot(
        [0, 1],
        [0, 1],
        linestyle="--",
        label="Perfect calibration"
    )

    # Actual credibility scorer calibration
    plt.plot(
        mean_predicted,
        mean_expected,
        marker="o",
        label="Credibility scorer"
    )

    # Labels and title
    plt.xlabel("Mean predicted score")
    plt.ylabel("Mean expected score")
    plt.title("Credibility Score Calibration")

    plt.legend()
    plt.grid(alpha=0.25)
    plt.tight_layout()

    # Save the graph
    plt.savefig(
        "credibility_calibration_plot.png",
        dpi=300,
        bbox_inches="tight"
    )

    # Display the graph
    plt.show()


# Generate the calibration plot
plot_calibration(expected_scores, predicted_scores)

