# -*- coding: utf-8 -*-
"""Aviation Data Analysis 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UeIuEGw_4EKf26JB8OFJfJsJhfrosRjo
"""

# Commented out IPython magic to ensure Python compatibility.
#Importing required librarys and funtions to complete this analysis
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
# %matplotlib inline

#Converting files to dataframes
df1 = pd.read_csv(r"C:\Users\deona\Downloads\Airport_Codes.csv")
df2 = pd.read_csv(r"C:\Users\deona\Downloads\Flights.csv", low_memory=False)
df3 = pd.read_csv(r"C:\Users\deona\Downloads\Tickets.csv")
df4 = pd.read_csv(r"C:\Users\deona\Downloads\airports.csv")
df1 = pd.DataFrame(df1)
flights = pd.DataFrame(df2)
tickets = pd.DataFrame(df3)
df4 = pd.DataFrame(df4)

#Renaming column to make merging process easier
df4.rename(columns={"iata":"IATA_CODE"},inplace = True)

#Merging airport files so dataframes contain needed data
airports = pd.merge(df1, df4, on="IATA_CODE")

#Merging dataframes on similiar columns
f1 = flights.merge(airports, left_on="ORIGIN", right_on="IATA_CODE", suffixes=("", "_ORIGIN"))

#Merging dataframes on similiar columns
flights = f1.merge(airports, left_on="DESTINATION", right_on="IATA_CODE",suffixes=("_ORIGIN", "_DEST"))

#Filtering dataframe so rows only include flights taken from medium and large airports
flights = flights[
    ((flights["TYPE_ORIGIN"] == "medium_airport") | (flights["TYPE_ORIGIN"] == "large_airport")) &
    ((flights["TYPE_DEST"] == "medium_airport") | (flights["TYPE_DEST"] == "large_airport"))
]

#Excluding flights that were cancelled
flights = flights[flights["CANCELLED"] == 0.0]

tickets["ITIN_FARE"] = pd.to_numeric(tickets["ITIN_FARE"], errors="coerce")

#Filtering dataframe so only roundtrips are included
roundtrip = tickets[tickets["ROUNDTRIP"] == 1.0]

#Only including roundtrip tickets for 1 passenger
roundtrip = roundtrip[roundtrip ["PASSENGERS"] == 1.0]

roundtrip1 = (roundtrip.groupby(["ORIGIN", "DESTINATION"])["ITIN_FARE"].mean().reset_index())

#Merging dataframes needed for analysis
flights_rt = pd.merge(
    flights,
    roundtrip1,
    on=["ORIGIN", "DESTINATION"])

flights_rt.head()

# Identifying the 10 busiest round-trip routes based on the number of round-trip flights in the quarter
tenbusiest = (
    flights_rt.groupby(["ORIGIN", "DESTINATION"])
      .size()
      .reset_index(name="Total Flights")
      .sort_values(by="Total Flights", ascending=False)
)

#Displaying the top 10 busiest flights
tenbusiest.head(10)

print(flights_rt.info())

#Creating a column to represent the baggage revenue for each flight
flights_rt["b_revenue"] = flights_rt["OCCUPANCY_RATE"]* 200 /2 * 70

#Changing name of existing column that represents flight price
flights_rt.rename(columns={"t_revenue":"Ticket_price"},inplace = True)

#Creating a column to represent the number passengers for each flight
flights_rt["Passengers"] = flights_rt["OCCUPANCY_RATE"]* 200

#Creating a column to represent the cost of Flight Ops for each flight
flights_rt["Flight_Ops"] = flights_rt["DISTANCE"]* 8

#Creating a column to represent the ticket revenue for each flight
flights_rt["t_revenue"] = flights_rt["Ticket_price"] * flights_rt["Passengers"]

#Creating a column to represent the profit made for each flight
flights_rt["Profit"] = (
    (flights_rt["t_revenue"] + flights_rt["b_revenue"])
    - (flights_rt["Flight_Ops"] + flights_rt["Overhead"] + flights_rt["Airportcost"])
)

flights_rt["Ticket_price"].value_counts()

flights_rt["t_revenue"]

flights_rt["Flight_Ops"]

#Creating a column to represent overhead prices per flight
flights_rt["Overhead"] = flights_rt["DISTANCE"]* 1.18

#Creating a column to represent Airport cost per flight
flights_rt["Airportcost_1"] = (
    flights_rt["TYPE_ORIGIN"]
        .replace({
            "large_airport": 10000,
            "medium_airport": 5000
        })
        .infer_objects(copy=False)
)

flights_rt["Airportcost_1"].value_counts()

#Creating a column to represent Airport cost per flight
flights_rt["Airportcost_2"] = (
    flights_rt["TYPE_DEST"]
        .replace({
            "large_airport": 10000,
            "medium_airport": 5000
        })
        .infer_objects(copy=False)
)

flights_rt["Airportcost_2"].value_counts()

#Creating a column to represent total Airport cost of a roundtrip flight
flights_rt["Airportcost"] = flights_rt["Airportcost_1"] + flights_rt["Airportcost_2"]

flights_rt["Airportcost"]

flights_rt["DEP_DELAY"]

flights_rt["ARR_DELAY"]

#Creating column to represent delay fee for flight arrivals
flights_rt["ARR_DELAY_FEES"] = 0

adelays = flights_rt["ARR_DELAY"] < -15

flights_rt.loc[adelays, "ARR_DELAY_FEES"] = (
    (flights_rt["ARR_DELAY"].abs() - 15) * 75
)

flights_rt["ARR_DELAY_FEES"]

#Creating column to represent delay fee for flight departures
flights_rt["DEP_DELAY_FEES"] = 0

ddelays = flights_rt["DEP_DELAY"] < -15

flights_rt.loc[ddelays, "DEP_DELAY_FEES"] = (
    (flights_rt["DEP_DELAY"].abs() - 15) * 75
)

flights_rt["DEP_DELAY_FEES"]

flights_rt["Ticket_price"]

#Sorting dataframe to display the the 5 best flights to invest in
Profitf = (flights_rt.sort_values(by="Profit", ascending=False).drop_duplicates(subset=["ORIGIN", "DESTINATION"]).reset_index(drop=True))

Profitf.head()

#3.a.i.
Suggested roundtrip routes
1. Origin Airport: SLC  Destination Airport :TWF
2. Origin Airport: EGE  Destination Airport :JFK
3. Origin Airport: FLO Destination Airport :CLT
4. Origin Airport: PIH  Destination Airport :SLC
5. Origin Airport: HNL  Destination Airport :GUM

Profitf["Break_even"] = 90000000 / Profitf["Profit"]

Profitf.head()

#Break-Even Analysis
Suggested roundtrip routes
1. Origin Airport: SLC  Destination Airport :TWF
46 flights to break even
2. Origin Airport: EGE  Destination Airport :JFK
218 flights to break even
3. Origin Airport: FLO Destination Airport :CLT
230 flights to break even
4. Origin Airport: PIH  Destination Airport :SLC
253 flights to break even
5. Origin Airport: HNL  Destination Airport :GUM
265 flights to break even

1. Financial KPIs

These recommendations will measure revenue and profitability.

a.Add the ticket and baggage revenue then group by flight . This would help identify high-value routes.

b.Compute the profit per flight , this Indicates financial efficiency.

2. Operational KPIs

This recommendation measure efficiency and punctuality.

a.Compute the percentage of flights with delays .

3. Customer / Ticketing KPIs

This recommendation measures customer experience and market performance.

Compute the passangers per flight , this would helps identify high-demand flights.

Flights200 = flights_rt.head(200)

Profitf = Profitf.sort_index(ascending=True)

Flights200 = Profitf.head(200)

#Shows how delays are distributed, highlighting on-time vs delayed flights
plt.figure(figsize=(10,6))
sns.histplot(Flights200['ARR_DELAY'], bins=30, kde=True, color='skyblue')
plt.title('Distribution of Arrival Delays')
plt.xlabel('Arrival Delay (minutes)')
plt.ylabel('Number of Flights')
plt.axvline(0, color='red', linestyle='--', label='On Time')
plt.legend()
plt.show()

# Creating graph to highlight the most profitable routes
route_revenue = flights_rt.groupby(['ORIGIN','DESTINATION'])[['t_revenue','b_revenue']].sum().reset_index()
route_revenue['Total_Revenue'] = route_revenue['t_revenue'] + route_revenue['b_revenue']

# Plot top 10 routes by revenue
top_routes = route_revenue.sort_values('Total_Revenue', ascending=False).head(10)

plt.figure(figsize=(12,6))
sns.barplot(x='Total_Revenue', y=top_routes['ORIGIN'] + ' → ' + top_routes['DESTINATION'], data=top_routes, palette='viridis')
plt.title('Top 10 Routes by Total Revenue')
plt.xlabel('Total Revenue')
plt.ylabel('Route')
plt.show()

#Creating graph to compare Average Arrival Delay by Origin Airport Type
avg_delay = flights_rt.groupby('TYPE_ORIGIN')['ARR_DELAY'].mean().reset_index()

plt.figure(figsize=(8,5))
sns.barplot(x='TYPE_ORIGIN', y='ARR_DELAY', data=avg_delay, palette='Set2')
plt.title('Average Arrival Delay by Origin Airport Type')
plt.xlabel('Airport Type')
plt.ylabel('Average Arrival Delay (minutes)')
plt.show()

"""#Next steps
The next steps would include caculating the ticket for empty seat for each flight , this show us how much money is lost per flight due to places not being fully booked . I would preform a deeper analysis to help route optimizations to identify underperforming vs high-performing routes. Also , I fit models to predict revenue and passenger numbers using historical trends.
"""

