# -*- coding: utf-8 -*-
"""COVID-19 Case Time Series Forecasting

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_q3TZNGExSNK3POyJ6WVY_3hBu9vPCv6
"""

#Importing libraries needed for the project
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats

from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.tsa.holtwinters import ExponentialSmoothing
from statsmodels.tsa.arima.model import ARIMA
from sklearn.metrics import mean_absolute_error, mean_squared_error

# Using pandas to load in CSV files
pd.set_option('display.float_format', lambda x: '%.6f' % x)
covid19 = pd.read_csv(r"C:\Users\deona\Downloads\covid19.csv",sep=';')

# Converting CSV file to dataframe
df = pd.DataFrame(covid19)

# Converting date column
df['Date_reported'] = pd.to_datetime(df['Date_reported'], dayfirst=True)

#Creating dataframe that only includes Europe data from years 2020-2022
Europe = df[(df['WHO_region'] == 'EURO') &
        (df['Date_reported'].dt.year >= 2020) &
        (df['Date_reported'].dt.year <= 2022)]

Europe.head()

# Aggregating total cases across Europe per day
EURO = Europe.groupby('Date_reported')['New_cases'].sum()

# Sorting index
EURO = EURO.sort_index()

EURO.head()

# Plotting graph to display cases trend
plt.figure(figsize=(12,5))
plt.plot(EURO, label='Daily Cases')
plt.title('COVID-19 Daily Cases in Europe (2020-2022)')
plt.xlabel('Date')
plt.ylabel('Cases')
plt.legend()
plt.show()

# Rolling Statistic
rolling_mean = EURO.rolling(window=7).mean()
rolling_std = EURO.rolling(window=7).std()

plt.figure(figsize=(12,5))
plt.plot(EURO, label='Original')
plt.plot(rolling_mean, label='7-day Rolling Mean')
plt.plot(rolling_std, label='7-day Rolling Std')
plt.legend()
plt.title('Rolling Statistics (2020-2022)')
plt.show()

# Seasonality decomposition
decomposition = seasonal_decompose(EURO, model='additive', period=7)

decomposition.plot()
plt.show()

# Train and test split
train_size = int(len(EURO) * 0.8)

train = EURO[:train_size]
test = EURO[train_size:]

# Creating baseline model
baseline_pred = test.shift(1)
baseline_pred.iloc[0] = train.iloc[-1]

# Fitting ARIMA model
arima_model = ARIMA(train, order=(2,0,2))
arima_fit = arima_model.fit()

arima_forecast = arima_fit.forecast(steps=len(test))

# Fitting Exponential Smoothing model
exp_model = ExponentialSmoothing(
    train,
    trend='add',
    seasonal='add',
    seasonal_periods=7
)

exp_fit = exp_model.fit()

exp_forecast = exp_fit.forecast(len(test))

# Forecast evaluation for each model
def evaluate(actual, predicted, name):
    mae = mean_absolute_error(actual, predicted)
    rmse = np.sqrt(mean_squared_error(actual, predicted))
    print(f"{name} -> MAE: {mae:.2f}, RMSE: {rmse:.2f}")

evaluate(test, baseline_pred, "Baseline")
evaluate(test, arima_forecast, "ARIMA")
evaluate(test, exp_forecast, "Exponential Smoothing")

# Plotting model forecast performance
plt.figure(figsize=(12,6))
plt.plot(train, label='Train')
plt.plot(test, label='Test')
plt.plot(arima_forecast, label='ARIMA Forecast')
plt.plot(exp_forecast, label='Exp Smoothing Forecast')
plt.legend()
plt.title('Forecast Comparison')
plt.show()

