# -*- coding: utf-8 -*-
"""persona.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IHNl2rLAiPkJcawNTlXfnXulWcCYyMk4
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional
from .llm import LLM
import yaml
# Where persona files live. Relative to wherever you launched the app.
DEFAULT_PERSONA_DIR = Path("temp")
"""
persona.py — a persona is a markdown file on disk.

That is the whole idea of this package. There is no persona database and no
in-memory registry. A persona is a `.md` file in `temp/`, and anything that can
read that file can wake the persona up. You can open one in a text editor,
change a sentence, and the agent behaves differently on the next run.

File format — frontmatter for the machine, markdown for the model:

    ---
    name: Maria Delgado
    role: patient
    summary: 58-year-old with poorly controlled type 2 diabetes
    ---

    # Maria Delgado

    ## Background
    ...

The frontmatter parser here is about fifteen lines and handles exactly the
three keys above. That is intentional — see YOUR TASK at the bottom.
"""

@dataclass
class PersonaSpec:
    """One persona: the metadata we index on, plus the markdown that is its mind."""

    name: str
    role: str
    summary: str
    body: str

    def slug(self) -> str:
        """Filesystem-safe stem, e.g. 'Maria Delgado' -> 'maria-delgado'."""
        s = re.sub(r"[^a-z0-9]+", "-", self.name.lower()).strip("-")
        return s or "unnamed"

    def to_markdown(self) -> str:
        """Serialize to the frontmatter + body format."""
        return (
            "---\n"
            f"name: {self.name}\n"
            f"role: {self.role}\n"
            f"summary: {self.summary}\n"
            "---\n\n"
            f"{self.body.strip()}\n"
        )

    # TASK 3
    @classmethod
    def from_markdown(cls, text: str) -> "PersonaSpec":
        """
        Use YAML frontmatter to parse a persona markdown file.

        Missing or malformed frontmatter is tolerated by falling
        back to safe default values.
        """

        meta = {
            "name": "Unnamed",
            "role": "unknown",
            "summary": "",
        }

        text = text.strip()

        # Remove an accidental markdown code fence.
        if text.startswith("```"):
            lines = text.splitlines()

            if lines and lines[-1].strip().startswith("```"):
                lines = lines[1:-1]
            else:
                lines = lines[1:]

            text = "\n".join(lines).strip()

        body = text

        if text.startswith("---"):
            rest = text[3:].lstrip("\n")
            closing = re.search(
                r"^---\s*$",
                rest,
                re.MULTILINE,
            )

            if closing:
                front = rest[:closing.start()]
                body = rest[closing.end():].strip()

                try:
                    parsed = yaml.safe_load(front)

                    if isinstance(parsed, dict):
                        for key in meta:
                            if key in parsed:
                                meta[key] = str(parsed[key]).strip()

                except yaml.YAMLError:
                    # Keep defaults if frontmatter is malformed.
                    pass

        return cls(
            name=meta["name"],
            role=meta["role"],
            summary=meta["summary"],
            body=body.strip(),
        )
# TASK 2
def save_persona(
    spec: PersonaSpec,
    directory: Path = DEFAULT_PERSONA_DIR,
) -> Path:
    """
    Save a persona without overwriting an existing persona.

    Duplicate files receive a numeric suffix:
    maria-delgado.md
    maria-delgado-2.md
    maria-delgado-3.md
    """
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)

    base_slug = spec.slug()
    path = directory / f"{base_slug}.md"

    counter = 2

    while path.exists():
        path = directory / f"{base_slug}-{counter}.md"
        counter += 1

    path.write_text(
        spec.to_markdown(),
        encoding="utf-8",
    )

    return path


def load_persona(path: Path) -> PersonaSpec:
    """Read one persona file from disk."""
    return PersonaSpec.from_markdown(
        Path(path).read_text(encoding="utf-8")
    )


def list_personas(
    directory: Path = DEFAULT_PERSONA_DIR,
) -> List[PersonaSpec]:
    """
    Return every persona currently saved,
    sorted by filename. Empty if none exist.
    """
    directory = Path(directory)

    if not directory.exists():
        return []

    return [
        load_persona(path)
        for path in sorted(directory.glob("*.md"))
    ]


# TASK 1
def find_persona(
    name: str,
    directory: Path = DEFAULT_PERSONA_DIR,
) -> Optional[PersonaSpec]:
    """
    Find a persona by exact name, slug, role,
    or unique partial name.

    Matching priority:
    1. Exact name
    2. Exact slug
    3. Exact role, only if one persona has that role
    4. Partial name, only if exactly one persona matches

    Ambiguous matches return None.
    """
    needle = name.strip().lower()
    personas = list_personas(directory)

    if not needle:
        return None

    # 1. Exact name
    exact_name = [
        spec
        for spec in personas
        if spec.name.lower() == needle
    ]

    if len(exact_name) == 1:
        return exact_name[0]

    # 2. Exact slug
    exact_slug = [
        spec
        for spec in personas
        if spec.slug() == needle
    ]

    if len(exact_slug) == 1:
        return exact_slug[0]

    # 3. Exact role
    role_matches = [
        spec
        for spec in personas
        if spec.role.lower() == needle
    ]

    if len(role_matches) == 1:
        return role_matches[0]

    if len(role_matches) > 1:
        return None

    # 4. Partial name
    partial_matches = [
        spec
        for spec in personas
        if needle in spec.name.lower()
    ]

    if len(partial_matches) == 1:
        return partial_matches[0]

    return None
# -----------------------------------------------------------------------------
# Generating a persona with the model
# -----------------------------------------------------------------------------

_AUTHOR_SYSTEM = """You write character specifications for a multi-agent simulation.

Given a short description, write a persona as a markdown document. Output ONLY the
markdown — no preamble, no code fences.

Use exactly this structure:

---
name: <a specific, realistic full name>
role: <one lowercase word, e.g. patient, doctor, teacher, customer>
summary: <one line, under 15 words>
---

# <name>

## Background
Two or three sentences. Be concrete and specific — age, situation, history.

## Personality
Three or four bullet points about temperament and outlook.

## How they speak
Two or three bullets on voice: vocabulary, sentence length, verbal habits.

## What they want
One or two sentences on their goal in a conversation.

## What they avoid
One or two sentences on what they will not say or do.

Write a specific individual, not a type. Give them a quirk. Avoid stereotypes,
and do not make them a spokesperson for a demographic."""
#TASK 4
def validate_persona(spec: PersonaSpec) -> List[str]:
    """
    Validates a generated persona.

    Returns a list of validation errors.
    An empty list means the persona is valid.
    """
    errors = []

    if not spec.name.strip() or spec.name == "Unnamed":
        errors.append("Persona must have a name.")

    if not spec.role.strip() or spec.role == "unknown":
        errors.append("Persona must have a role.")

    if len(spec.role.split()) != 1:
        errors.append("Role must be one word.")

    required_sections = [
        "## Background",
        "## Personality",
        "## How they speak",
        "## What they want",
        "## What they avoid",
    ]

    for section in required_sections:
        if section.lower() not in spec.body.lower():
            errors.append(f"Missing required section: {section}")

    return errors

def generate_persona(description: str, llm: LLM) -> PersonaSpec:
    """
    Ask the model to author a persona from a one-line description.

    The model may occasionally ignore the requested markdown format.
    Generation should still return a usable PersonaSpec rather than
    crashing the application.
    """

    markdown = llm.complete(
        system=_AUTHOR_SYSTEM,
        messages=[
            {
                "role": "user",
                "content": f"Write a persona for: {description}",
            }
        ],
        max_tokens=2048,
    )

    spec = PersonaSpec.from_markdown(markdown)

    # -------------------------------------------------------------
    # Fallback name
    # -------------------------------------------------------------
    if not spec.name or spec.name == "Unnamed":
        spec.name = description[:40].strip().title() or "Unnamed"

    # -------------------------------------------------------------
    # Fallback role
    # -------------------------------------------------------------
    if not spec.role or spec.role == "unknown":
        words = description.strip().split()

        if words:
            # Remove a leading article when possible.
            if words[0].lower() in {"a", "an", "the"} and len(words) > 1:
                spec.role = words[1].lower()
            else:
                spec.role = words[0].lower()
        else:
            spec.role = "person"

    # -------------------------------------------------------------
    # Fallback summary
    # -------------------------------------------------------------
    if not spec.summary:
        spec.summary = description.strip()

    # -------------------------------------------------------------
    # Preserve whatever body the model returned.
    # -------------------------------------------------------------
    if not spec.body.strip():
        spec.body = markdown.strip() or description.strip()

    return spec